### ISSUE TITLE
dets: storage path

### ISSUE THREAD

**Issue by vishal-h** [Schultzer/ecto_qlc#2]
I was trying this out and works fine with ETS and DETS. But in case of DETS are there any additional steps needed to persist? I couldn't find anything in docs. Sorry if I am missing something quite obvious.

**Comment by Schultzer** [comment]
Hi @vishal-h, you can set the `dir` for DETS with: 

```elixir
config :dets, dir: ~c"~/home"
```

I'm using that in the test suite to create the table files in a tmp folder here: https://github.com/Schultzer/ecto_qlc/blob/f08a02d1dfdf652e7e6c3dc9420b9af9299943b2/test/support/data_case.ex#L41C32-L41C36.

Ecto.QLC should respect all configurations made to `:dets`, as an example, when creating a table: https://github.com/Schultzer/ecto_qlc/blob/main/lib/ecto/adapters/qlc.ex#L269-L280.

Please take a look at https://www.erlang.org/doc/man/dets for more in-depth documentation of ways to configure `:dets`.

**Comment by vishal-h** [comment]
config/config.exs
```bash
import Config

config :dets, dir: ~c"~/home/livebook"
```

```
Mix.install(
  [
    {:ecto_qlc, "~> 0.1.0"}
  ],
  config: Config.Reader.read!("#{__DIR__}/config/config.exs")
)
```

```
defmodule Db.Migration do
  use Ecto.Migration

  def change do
    create table(:jobs) do
      add(:completed_at, :utc_datetime_usec)
      add(:started_at, :utc_datetime_usec)
      add(:mfa, {:array, :any})
      timestamps()
    end
  end
end

defmodule Db.Repo do
  use Ecto.Repo, otp_app: :some_app, adapter: EctoQLC.Adapters.DETS
end
```

```
alias Db.Repo
alias Db.Migration

Repo.start_link([])
Ecto.Migrator.up(Repo, 1, Migration)
```

the above code is throwing the error below

 (ArgumentError) argument error
    (stdlib 4.0.1) dets.erl:1259: :dets.safe_fixtable(:"Elixir.EctoQLC.Adapters.DETS.schema_migrations", true)
    (stdlib 4.0.1) qlc.erl:3806: :qlc.call/4
    (stdlib 4.0.1) qlc.erl:2663: :qlc.table_handle/3
    (stdlib 4.0.1) qlc.erl:2428: :qlc.setup_le/3
    (stdlib 4.0.1) qlc.erl:295: :qlc.eval/2
    (stdlib 4.0.1) timer.erl:266: :timer.tc/3
    (ecto_qlc 0.1.0) lib/ecto/adapters/qlc.ex:227: EctoQLC.Adapters.QLC.execute/5
    (ecto 3.9.6) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.9.6) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:514: anonymous fn/5 in Ecto.Migrator.lock_for_migrations/4
    (kernel 8.4.1) global.erl:463: :global.trans/4
    (ecto_qlc 0.1.0) lib/ecto/adapters/qlc.ex:414: EctoQLC.Adapters.QLC.lock_for_migrations/3
    (ecto_sql 3.9.2) lib/ecto/migrator.ex:513: Ecto.Migrator.lock_for_migrations/4**

**Comment by Schultzer** [comment]
Thanks for the report, can you please try with master.

```
Mix.install(
  [
    {:ecto_qlc, github: "schultzer/ecto_qlc"}
  ],
  config: Config.Reader.read!("#{__DIR__}/config/config.exs")
)
```

**Comment by vishal-h** [comment]
Sorry same issue. However the error contains (ecto_sql 3.11.1) instead of (ecto_sql 3.9.2)

**Comment by Schultzer** [comment]
It looks like a file permission issue; ensure the directory exists, and you can write to it.


Below is an example of how to set DETS to use your system tmp directory. 
```
dets_dir = '#{Path.join(System.tmp_dir!(), "ecto-qlc-#{Ecto.UUID.generate}")}'
File.mkdir(dets_dir)
Application.put_env(:dets, :dir, dets_dir)
```

**Comment by vishal-h** [comment]
Huh! The above code works. Not sure how the livebook permissions work. Will dig further.

Thanks for your help!
